### PR TITLE
Update Deps / Playback / Subtitles / Refactor

### LINKED ISSUE #23: Is it possible to change playback speed while casting?
Hi,
Thank you so much for this awesome plugin. I was just wondering if it is possible to change playback speed of the casted audio/video? I couldn't find it anywhere in the code. 
Thanks!

### LINKED ISSUE #34: Not compatible with http: ^0.13.0
Not compatible with http: ^0.13.0

### PR DESCRIPTION
**Pull request by Saifallak**
this PR have changes in #38 also (#29 and i think part of it the same as #24)

also updating deps and removed unsued overrides (it's not override anymore anyway)

pump version and here we are.

Fixes #34
Fixes #23

### CODE REVIEW

**Comment by dgilperez** [comment]
Interesting! Needs a rebase after null version is here (yeeha!)

**Comment by terrabythia** [comment]
@Saifallak basically the same comments as in [this PR](https://github.com/terrabythia/dart_chromecast/pull/29#issuecomment-1008066555). Could you add an example?

**Comment by Saifallak** [comment]
Will try in next days..

Sorry, abit busy.

**Comment by guyluz11** [comment]
Hi @Saifallak 
It looks like some of the things in this pr got merged by other prs.

So only #29 functionality is still needed to be implemented from here.

Maybe it will be better if you will recreate your pr only with the missing features since it passed so much time.

**Comment by Saifallak** [comment]
> Hi @Saifallak It looks like some of the things in this pr got merged by other prs.
> 
> So only #29 functionality is still needed to be implemented from here.
> 
> Maybe it will be better if you will recreate your pr only with the missing features since it passed so much time.

It was 2 years ago, currently not using it anymore, and sadly don't have time to contribute

**Pull request closed without merging**
