### PR TITLE
add implementation of abstract methods on GeneratedMessage

### PR DESCRIPTION
**Pull request by Thnslj**

### CODE REVIEW

**Comment by SwaXTech** [comment]
Hi, can you see the friendly name of the chromecast? It does not appear to me.

**Comment by Thnslj** [comment]
> Hi, can you see the friendly name of the chromecast? It does not appear to me.

No we also have that issue. But that have nothing to to with this PR.

**Comment by snaeji** [comment]
Check out this thread and the Wilsharo's fork
https://github.com/flutter/flutter/issues/18212

**Comment by terrabythia** [comment]
Hi Thnslj

Sorry for the late response. From what I can see you've added the `createEmptyInstance` methods by hand. This is indeed a fix, but the code you are editing is code generated by protobuf (see https://github.com/dart-lang/protobuf). 

I've now regenerated the code via the protoc tool and the problem is fixed. Thanks for your input though, I haven't really had the time to fix any problems with this package myself lately.

**Pull request closed without merging**
